# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=40)),
                ('Nombre de Tweet', models.IntegerField()),
                ('Recherche', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TweetSAAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=40)),
                ('Positive Tweets', models.IntegerField()),
                ('Negative Tweets', models.IntegerField()),
            ],
        ),
    ]
